version: "3"
services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_CONTEXT=spark://spark-master:7077
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
    command:
      bash -c "cp /tmp/spark-config/log4j.properties /spark/conf/log4j.properties \
      && /spark/bin/spark-class org.apache.spark.deploy.master.Master \
      --ip spark-master --port 7077 --webui-port 8080"
    volumes:
      - ./scripts:/run
      - ./target:/app
      - ./resources/spark-config:/tmp/spark-config
    networks:
      - my-network
    working_dir: /run

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_LOCAL_IP=spark-worker-1
      - SPARK_MASTER_HOST=spark-master
    command:
      bash -c "/spark/bin/spark-class org.apache.spark.deploy.worker.Worker \
      --ip spark-worker-1 --memory 2g --cores 2 --webui-port 8081 spark://spark-master:7077"
    networks:
      - my-network

  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_LOCAL_IP=spark-worker-2
      - SPARK_MASTER_HOST=spark-master
    command:
      bash -c "/spark/bin/spark-class org.apache.spark.deploy.worker.Worker \
      --ip spark-worker-2 --memory 2g --cores 2 --webui-port 8082 spark://spark-master:7077"
    networks:
      - my-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
